config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :groups do
      post 'join', on: :member
      resources :comments, only: %i[create]
    end
  end
  post 'select_game', to: 'home#select_game', as: 'select_game'
  devise_for :users
  root 'home#index'
  resources :profiles, path: '/profile', param: :username do
    resources :comments, only: %i[create]
    resources :thumbs, only: %i[create]
  end
  namespace :load_test do
    get 'sign_in_as_new_user'
    get 'seed_games'
    get 'seed_groups/:num_games/:num_groups' => '/load_test#seed_groups'
    get 'seed_users/:num_users' => '/load_test#seed_users'
    get 'reset_table/:table' => '/load_test#reset_table'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_username(params[:username])
    return not_found unless @user

    @thumbup_num = @user.thumbs.sum(:value)
    @editable = true if current_user == @user
  end

  def edit
    authenticate_user!

    @user = User.find_by_username(params[:username])
    return not_found unless @user

    redirect_to profile_path(@user) unless current_user == @user
  end

  def update
    authenticate_user!

    @user = User.find_by_username(params[:username])
    return not_found unless @user

    return redirect_to profile_path(@user), alert: "You cannot edit another user's profile!" unless current_user == @user

    if @user.update(user_params)
      redirect_to profile_path(@user)
    else
      render :edit
    end

  end

  private

  def user_params
    params.require(:user).permit(:bio)
  end
end

app/views/profiles/edit.html.erb
<div class="container mx-auto">
  <%= render 'home/titlebar' %>

  <div class="flex mt-16">
    <div class="flex px-10 py-6 bg-gray-800 rounded-t-sm">
      <label>Profile</label>
    </div>

    <div class="flex flex-grow justify-end bg-gray-800"><div class="flex flex-grow justify-end pr-6 bg-gray-900 rounded-bl-sm"></div></div>
  </div>

  <div class="bg-gray-800 rounded-tr-sm rounded-b-sm py-10 px-8">
    <%# Title Section %>
    <%= form_with model: @user, url: profile_path do |form| %>
    <div class="flex border-b border-gray-600 py-4">
      <div class="flex flex-grow flex-col">
        <h1 class="font-medium text-2xl"><%= @user.username %></h1>
      </div>
      <div class="flex">
        <%= link_to 'Back', :back, class: "edit-button ml-4"%>
        <%= form.submit class: "edit-button ml-4"%>
      </div>
    </div>
    
    <div class="py-4">
      <%= form.label :bio, class: "text-gray-400 pb-2"%><br>
      <%= form.text_area :bio %><br>
    <div>
      
  <% end %>
</div>



  
  
    

app/views/profiles/show.html.erb
<h1>
  Username: <%= @user.username %>
</h1>
<p>
  Bio: <%= @user.bio %>
</p>
<% if @editable %>
  <%= link_to 'edit', edit_profile_path(@user) %>
<% end %>

<h2>Upvote</h2>
<p>
Total Upvote: <%= @thumbup_num %>
</p>

<%= render 'thumbs/form', target: profile_thumbs_path(@user) %>


<h2>Add a comment:</h2>
<%= render 'comments/form', target: profile_comments_path(@user) %>

<h2>Comments</h2>
<%= render @user.comments %>