config/routes.rb
Rails.application.routes.draw do
  resources :games do
    resources :groups do
      post 'join', on: :member
      resources :comments, only: %i[create]
    end
  end
  post 'select_game', to: 'home#select_game', as: 'select_game'
  devise_for :users
  root 'home#index'
  resources :profiles, path: '/profile', param: :username do
    resources :comments, only: %i[create]
    resources :thumbs, only: %i[create]
  end
  namespace :load_test do
    get 'sign_in_as_new_user'
    get 'seed_games'
    get 'seed_groups/:num_games/:num_groups' => '/load_test#seed_groups'
    get 'seed_users/:num_users' => '/load_test#seed_users'
    get 'reset_table/:table' => '/load_test#reset_table'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  validates :max_member_count, numericality: { greater_than_or_equal_to: 2 }

  belongs_to :game, touch: true
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships
  has_many :comments, as: :commentable, dependent: :destroy

  alias_attribute :members, :users
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @filter = { game_id: params[:game_id] }
    params.each do |key, value|
      if key.end_with?('filter') && params[key].present?
        filter_name = key.delete_suffix('_filter')
        @filter[filter_name] = value
      end
    end
    @game = Game.find(params[:game_id])
    @pagy, @groups = pagy(Group.where(@filter))

    if params['search'].present?
      @groups = @groups.where('description ILIKE ?', "%#{params['search']}%")
      @search = params['search']
    end
  end

  # GET /groups/1 or /groups/1.json
  def show
    @game = Game.find(params[:game_id])
  end

  # GET /groups/new
  def new
    @game = Game.find(params[:game_id])
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @game = @group.game
  end

  # POST /groups or /groups.json
  def create
    authenticate_user!

    @game = Game.find(params[:game_id])
    @group = @game.groups.create(group_params)
    @group.group_memberships.create(user: current_user, owner: true)

    respond_to do |format|
      if @group.save
        format.html { redirect_to game_group_url(@game, @group), notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
    authenticate_user!

    game = Game.find(params[:game_id])
    group = Group.find(params[:id])

    return redirect_to game_group_url(game, group), notice: 'You are already a member of this group!' if group.members.exists?(current_user.id)
    return redirect_to game_group_url(game, group), notice: 'This group is already full' if group.members.size > group.max_member_count

    group.members << current_user

    redirect_to game_group_url(game, group), notice: "You are now a member of #{group.group_name}"
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    @game = @group.game
    respond_to do |format|
      if group_params[:join]
        if @group.current_member_count >= @group.max_member_count
          format.html { redirect_to game_group_url(@game, @group), notice: "You cannot join a full group!" }
        elsif @group.update(current_member_count: @group.current_member_count + 1)
          format.html { redirect_to game_group_url(@game, @group), notice: "Join success" }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @group.errors, status: :unprocessable_entity }
        end
      elsif @group.update(group_params)
        format.html { redirect_to game_group_url(@game, @group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    # @group.destroy
    @game = Game.find(@group.game_id)
    @game.groups.destroy(@group)
    respond_to do |format|
      format.html { redirect_to game_groups_url(@game), notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.require(:group).permit(:group_name, :activity, :description, :leader_name, :max_member_count, :game_id, :join)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
  <%# Groups Title %>
  <div class="flex mt-16">
    
    <div class="flex px-10 py-6 bg-gray-800 rounded-t-sm">
      <label for="games"><%= link_to @game.name, game_groups_path(@game) %></label>
    </div>

    <div class="flex flex-grow justify-end bg-gray-800">
      <div class="flex flex-grow justify-end pr-6 bg-gray-900 rounded-bl-sm">
        <%#= link_to 'Back', root_path %>
        <%# <button class="border-blue-300 bg-blue-500 bg-opacity-60 border  self-center py-2 px-8 hover:bg-blue-400 hover:bg-opacity-60 ml-6">Create Team</button> %>
      </div> 
    </div>
  </div>

  <div class="bg-gray-800 rounded-tr-sm rounded-b-sm py-10 px-8">
    <%# Title Section %>
    <%= form_with model: [@game, @group] do |form| %>
    <div class="flex border-b border-gray-600 py-4">
      <div class="flex flex-grow">
      </div>
      <div class="flex">
        <%= link_to 'Cancel', :back, class: "edit-button ml-4" %>
        <%= form.submit class: "edit-button ml-4 "%>
      </div>
    </div>

    
    <% if group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% group.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field mt-4 flex">
      <%= form.label :group_name, "Group Name:", class: "text-gray-300 self-center w-32"%>
      <%= form.text_field :group_name, class: "ml-4 px-2 py-1 bg-gray-700"%>
    </div>

    <div class="field mt-4 flex">
      <%= form.label :max_member_count, "Max Number:", class: "text-gray-300 self-center w-32" %>
      <%= form.number_field :max_member_count, min: 2, class: "ml-4 px-2 py-1 bg-gray-700" %>
    </div>

    <div class="field mt-4 flex">
      <%= form.label :description, "Description:", class: "text-gray-300 self-center w-32" %>
      <%= form.text_field :description, class: "ml-4 px-2 py-1 bg-gray-700" %>
    </div>

    <div class="field mt-4 flex">
      <%= form.label :activity, "Activity:", class: "text-gray-300 self-center w-32" %>
      <%= form.text_field :activity, class: "ml-4 px-2 py-1 bg-gray-700" %>
    </div>

    
  <% end %>
  
  </div>

app/views/groups/_group.html.erb
<p>
  <strong>Name:</strong>
  <%= group.group_name %>
</p>

<p>
  <strong>Number:</strong>
  <%= group.current_member_count %> / <%= group.max_member_count %>
</p>

<br>

app/views/groups/edit.html.erb
<div class="container mx-auto">
<%= render 'home/titlebar' %>
<%= render 'form', group: @group %>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<h4>Activity</h4>
<%= form_with url: game_groups_path, method: "get" do |f| %>
  <% ["activity", "max_member_count"].each do |filter| %>
    <%= f.collection_select "#{filter}_filter", Group.select(filter).where(game_id: @game.id).distinct, filter, filter, { include_blank: "All #{filter.capitalize}", selected: @filter[filter] } %>
  <% end %>

  <%= f.label :search %>
  <%= f.text_field :search, value: @search %>

  <%= f.submit "Apply Filters" %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.group_name %></td>
        <td><%= group.activity %></td>
        <td><%= link_to 'Show', game_group_path(@game, group) %></td>
        <td><%= link_to 'Edit', edit_game_group_path(@game, group) %></td>
        <td><%= link_to 'Delete', game_group_path(@game, group), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%== pagy_nav(@pagy) %>

<br>

<%= link_to 'New Group', new_game_group_path(@game) %>
<%= link_to 'Back', root_path %>

app/views/groups/new.html.erb
<div class="container mx-auto">
    <%= render 'home/titlebar'%>
    <%= render 'form', group: @group %>
</div>

app/views/groups/show.html.erb
<% cache @group do %>
  <h1>Current Group: <%= @group.group_name%></h1>
  <h2>Group ID: <%= @group.id%></h2>
  <h2>Max Number: <%= @group.max_member_count%></h2>
  <h2>Members (<%= @group.members.size %>)</h2>
  <ul>
    <% @group.group_memberships.each do |m| %>
      <li><%= m.user.username %><%= ' (Owner)' if m.owner? %></li>
    <% end %>
  </ul>
  <h2>Description: <%= @group.description%></h2>
  <h2>Activity: <%= @group.activity%></h2>
  <h2>Game: <%= @game.name%></h2>
  <%= button_to 'Join Group', join_game_group_path(@game, @group), method: :post %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form', target: game_group_comments_path(@game, @group) %>

  <h2>Comments</h2>
  <%= render @group.comments %>

  <%= link_to 'Edit', edit_game_group_path(@group) %> |
  <%= link_to 'Back', game_groups_path(@game) %>
<% end %>